paths:
  beep: "../Chip-8/assets/beep.mp3"
  rom: "../Chip-8/assets/example.ch8"
  fonts: "../Chip-8/assets/chip8.font"

debug:
  on: "false"
  file: "PONG.json"

test:
  expectedStateROM1: "../fixtures/PONG.json"
  expectedStateROM2: "../fixtures/IBM_Logo.json"
  ROM1: "../assets/PONG.ch8"
  ROM2: "../assets/IBM_Logo.ch8"
  FONT: "../assets/chip8.font"


